sudo: required

services:
  - docker

language: cpp

before_install:
- docker pull aberaud/opendht-deps
- docker pull aberaud/opendht-deps-llvm

script:
- docker build -f docker/DockerfileTravis .
- docker build -f docker/DockerfileTravisLlvm .

notifications:
  email:
      - adrien.beraud@savoirfairelinux.com
